language: c
sudo: required
dist: trusty

env:
  - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y gfortran libhdf5-dev hdf5-tools

script:
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy
  - python -c 'import numpy'
  - pip install h5py
  - python -c 'import h5py'
  - ./scripts/download_and_build_hdf5.sh 1>hdf5_build.out 2>&1
  - mkdir build && cd build
  - HDF5_ROOT=../_hdf5-1.8.17 cmake ..
  - make VERBOSE=1
  - ctest -V
  - sudo make install
  - rmpcdmd run single_dimer_pbc ../test/dimer_test.parameters dimer_test.h5 2296809391484081013
  - python ../test/dimer_test.py dimer_test.h5

after_failure:
  - h5dump -d /particles/dimer/position/value dimer_test.h5
  - h5dump -d /observables/temperature/value dimer_test.h5
  - h5dump -d /observables/potential_energy/value dimer_test.h5
  - cat ../hdf5_build.out
